# Generated by Django 5.0.2 on 2025-02-24 18:58

import app1.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultStyleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_type', models.CharField(choices=[('Computer Modern', 'Default (Computer Modern)'), ('Times New Roman', 'Times New Roman'), ('Arial', 'Arial')], default='Computer Modern', max_length=32)),
                ('font_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='black', max_length=32)),
                ('wall_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='black', max_length=32)),
                ('door_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='black', max_length=32)),
                ('furniture_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='black', max_length=32)),
                ('window_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='black', max_length=32)),
                ('sensor_label_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='teal', max_length=32)),
                ('camera_label_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='blue!75!black', max_length=32)),
                ('navigation_arrow_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='green!60!black', max_length=32)),
                ('calibration_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='violet', max_length=32)),
                ('wall_width', models.IntegerField(default=2)),
                ('door_width', models.IntegerField(default=1)),
                ('furniture_width', models.IntegerField(default=0.5)),
                ('window_width', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=500)),
                ('parent_directory', models.CharField(blank=True, max_length=255, null=True)),
                ('full_path', models.CharField(blank=True, max_length=500, null=True)),
                ('folders', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConvertedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='name', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('file_path', models.CharField(default='NONE', max_length=255)),
                ('temporary', models.BooleanField(default=False)),
                ('latex_file', models.CharField(default='/mnt/c/Users/Duayn/OneDrive/Documents/Obsidian Vault/Classes/CSCE 492/Generator v2/Layout_Generator/layoutGenerator/uploads/conversion_output/output.tex', max_length=255)),
                ('pdf_file', models.CharField(default='/mnt/c/Users/Duayn/OneDrive/Documents/Obsidian Vault/Classes/CSCE 492/Generator v2/Layout_Generator/layoutGenerator/uploads/conversion_output/output.pdf', max_length=255)),
                ('image', models.CharField(default='/mnt/c/Users/Duayn/OneDrive/Documents/Obsidian Vault/Classes/CSCE 492/Generator v2/Layout_Generator/layoutGenerator/uploads/conversion_output/output.png', max_length=255)),
                ('csv_file', models.CharField(blank=True, max_length=255, null=True)),
                ('json_file', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.folder')),
            ],
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(choices=[('above', 'Above'), ('below', 'Below'), ('left', 'Left'), ('right', 'Right')], default='above', max_length=5)),
                ('type', models.CharField(default='Sensor', max_length=20)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.convertedfile')),
            ],
        ),
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood', models.CharField(max_length=255)),
                ('building', models.CharField(max_length=255)),
                ('room_name', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('step', models.IntegerField(default=24)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='layout_reference', to='app1.convertedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='convertedfile',
            name='layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.layout'),
        ),
        migrations.CreateModel(
            name='LayoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('RENAME', 'Renamed'), ('EDIT', 'Edited'), ('MOVE', 'Moved'), ('CONVERT', 'Converted')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('old_value', models.CharField(blank=True, max_length=255)),
                ('new_value', models.CharField(max_length=255)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.convertedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Wall', 'Wall'), ('Door', 'Door'), ('Window', 'Window'), ('Furniture', 'Furniture'), ('Calibration', 'Calibration'), ('Camera', 'Camera'), ('Room Navigation', 'Room Navigation'), ('Sensor', 'Sensor')], max_length=100)),
                ('descriptor', models.CharField(blank=True, max_length=255, null=True)),
                ('x', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('y', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('radius', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scale', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rotation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('furniture_type', models.CharField(blank=True, choices=[('Rectangle', 'Rectangle'), ('Circle', 'Circle')], max_length=100, null=True)),
                ('room_navigation_direction', models.CharField(blank=True, choices=[('Left', 'Left'), ('Right', 'Right'), ('Up', 'Up'), ('Down', 'Down')], max_length=100, null=True)),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='app1.layout')),
            ],
        ),
        migrations.CreateModel(
            name='StyleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=64)),
                ('font_type', models.CharField(choices=[('Computer Modern', 'Default (Computer Modern)'), ('Times New Roman', 'Times New Roman'), ('Arial', 'Arial')], default='Computer Modern', max_length=32)),
                ('font_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='black', max_length=32)),
                ('wall_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='black', max_length=32)),
                ('door_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='black', max_length=32)),
                ('furniture_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='black', max_length=32)),
                ('window_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='black', max_length=32)),
                ('sensor_label_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='teal', max_length=32)),
                ('camera_label_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='blue!75!black', max_length=32)),
                ('navigation_arrow_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='green!60!black', max_length=32)),
                ('calibration_color', models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('green!60!black', 'Dark Green'), ('blue', 'Blue'), ('blue!75!black', 'Dark Blue'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('yellow', 'Yellow'), ('black', 'Black'), ('gray', 'Gray'), ('white', 'White'), ('darkgray', 'Dark Gray'), ('lightgray', 'Light Gray'), ('brown', 'Brown'), ('lime', 'Lime'), ('olive', 'Olive'), ('orange', 'Orange'), ('pink', 'Pink'), ('purple', 'Purple'), ('teal', 'Teal'), ('violet', 'Violet')], default='violet', max_length=32)),
                ('wall_width', models.IntegerField(default=2)),
                ('door_width', models.IntegerField(default=1)),
                ('furniture_width', models.IntegerField(default=0.5)),
                ('window_width', models.IntegerField(default=1)),
                ('meta_title', models.CharField(default='Layout', max_length=64)),
                ('meta_date', models.DateField(default=django.utils.timezone.now)),
                ('meta_location', models.TextField(blank=True, default='Address', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='convertedfile',
            name='style_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.stylesettings'),
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, default='placeholder.txt', null=True, upload_to=app1.models.get_user_subfolder, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xlsx', 'json', 'csv', 'xls'])])),
                ('file_name', models.CharField(default='', max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='folder',
            name='files',
            field=models.ManyToManyField(to='app1.uploadedfile'),
        ),
        migrations.AddField(
            model_name='convertedfile',
            name='uploaded_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.uploadedfile'),
        ),
        migrations.AlterUniqueTogether(
            name='folder',
            unique_together={('user', 'full_path')},
        ),
    ]
