# Generated by Django 5.0.2 on 2025-02-25 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedfile',
            name='image',
            field=models.CharField(default='/mnt/c/Users/Brandon Hucks/My Drive/Linux/CSCE490/Layout_Generator/layoutGenerator/uploads/conversion_output/output.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='convertedfile',
            name='latex_file',
            field=models.CharField(default='/mnt/c/Users/Brandon Hucks/My Drive/Linux/CSCE490/Layout_Generator/layoutGenerator/uploads/conversion_output/output.tex', max_length=255),
        ),
        migrations.AlterField(
            model_name='convertedfile',
            name='pdf_file',
            field=models.CharField(default='/mnt/c/Users/Brandon Hucks/My Drive/Linux/CSCE490/Layout_Generator/layoutGenerator/uploads/conversion_output/output.pdf', max_length=255),
        ),
        migrations.CreateModel(
            name='CanvasLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
