# Generated by Django 5.0.2 on 2025-03-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_convertedfile_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='height',
            new_name='length',
        ),
        migrations.AlterField(
            model_name='convertedfile',
            name='image',
            field=models.CharField(default='/mnt/c/Users/Duayn/OneDrive/Documents/Obsidian Vault/Classes/CSCE 492/Generator v2/Layout_Generator/layoutGenerator/uploads/conversion_output/output.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='convertedfile',
            name='latex_file',
            field=models.CharField(default='/mnt/c/Users/Duayn/OneDrive/Documents/Obsidian Vault/Classes/CSCE 492/Generator v2/Layout_Generator/layoutGenerator/uploads/conversion_output/output.tex', max_length=255),
        ),
        migrations.AlterField(
            model_name='convertedfile',
            name='pdf_file',
            field=models.CharField(default='/mnt/c/Users/Duayn/OneDrive/Documents/Obsidian Vault/Classes/CSCE 492/Generator v2/Layout_Generator/layoutGenerator/uploads/conversion_output/output.pdf', max_length=255),
        ),
    ]
