# Generated by Django 5.0.2 on 2025-04-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_height_measurement_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedfile',
            name='image',
            field=models.CharField(default='/mnt/c/Users/Brandon Hucks/My Drive/Linux/CSCE490/Layout_Generator/layoutGenerator/uploads/conversion_output/output.png', max_length=255),
        ),
        migrations.AlterField(
            model_name='convertedfile',
            name='latex_file',
            field=models.CharField(default='/mnt/c/Users/Brandon Hucks/My Drive/Linux/CSCE490/Layout_Generator/layoutGenerator/uploads/conversion_output/output.tex', max_length=255),
        ),
        migrations.AlterField(
            model_name='convertedfile',
            name='pdf_file',
            field=models.CharField(default='/mnt/c/Users/Brandon Hucks/My Drive/Linux/CSCE490/Layout_Generator/layoutGenerator/uploads/conversion_output/output.pdf', max_length=255),
        ),
        migrations.AlterField(
            model_name='defaultstylesettings',
            name='furniture_width',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=3),
        ),
        migrations.AlterField(
            model_name='stylesettings',
            name='furniture_width',
            field=models.DecimalField(decimal_places=1, default=0.5, max_digits=3),
        ),
    ]
